# Configuration for Rasa NLU.
    # https://rasa.com/docs/rasa/nlu/components/
language: en
pipeline:
- name: SpacyNLP
  model: "en_core_web_md"
- name: SpacyTokenizer
- name: SpacyEntityExtractor
  
- name: SpacyFeaturizer
  pooling: mean
- name: CountVectorsFeaturizer
  analyzer: char_wb
  min_ngram: 1
  max_ngram: 2
- name: SklearnIntentClassifier


policies:
  - name: MemoizationPolicy
  - name: KerasPolicy
  - name: MappingPolicy